In [0]:
# NumPy : numerical python, array, mathematical operation!
# pythonic data types : list tuples sets dict
# numpy : array

In [0]:
# Why Pandas?

# How many of you have used excel? Excel has limitation when data is large.

# Suppose :
# 50 million customers
# 100 csv files
# Need some automation

# Using excel in this scenario becomes challenging.

# Pandas allows us to :
# 1. Read data
# 2. Clean data
# 3. Transform data
# 4. Analyse data
# 5. Export results

# Think of Pandas - Excel of Steroids using python!

In [0]:
# What is structured data?
# Rows and columns (Tabular Data)

In [0]:
import numpy  as np
import pandas as pd

In [0]:
# 1. Series : One column!
age = pd.Series([20,22,24,26,28,30,32])
print(age)

0    20
1    22
2    24
3    26
4    28
5    30
6    32
dtype: int64

In [0]:
# A series has 2 things : i) Index ii) Values

In [0]:
# 2. Dataframe : Multiple Series together!
students = pd.DataFrame(
    {
        'Name' : ['a','b','c','d','e'],
        'Age'  : [20,30,40,50,60],
        'Marks': [80,70,60,50,40]
    }
)

In [0]:
students

  Name  Age  Marks
0    a   20     80
1    b   30     70
2    c   40     60
3    d   50     50
4    e   60     40

In [0]:
type(students)

pandas.core.frame.DataFrame

In [0]:
students['Name'] # fetch name column from a student df

0    a
1    b
2    c
3    d
4    e
Name: Name, dtype: object

In [0]:
type(students['Name'])

pandas.core.series.Series

In [0]:
students['Name'].values

array(['a', 'b', 'c', 'd', 'e'], dtype=object)

In [0]:
sales = pd.DataFrame({
    "OrderID":[101,102,103,104,105,106],
    "Customer":["Sankara","Priya","Rohit","Sneha","Rahul","Neha"],
    "City":["Delhi","Mumbai","Delhi","Pune","Delhi","Mumbai"],
    "Category":["Laptop","Phone","Tablet","Laptop","Phone","Tablet"],
    "Quantity":[2,1,3,1,2,5],
    "Price":[75000,45000,30000,80000,50000,25000]
})

sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.head() # default : first 5 rows

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000

In [0]:
sales.head(1) # first row

   OrderID Customer   City Category  Quantity  Price
0      101  Sankara  Delhi   Laptop         2  75000

In [0]:
sales.tail() # default : last 5 rows

   OrderID Customer    City Category  Quantity  Price
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.tail(1) # last row in the output

   OrderID Customer    City Category  Quantity  Price
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.shape
# rows, columns

(6, 6)

In [0]:
sales.columns

Index(['OrderID', 'Customer', 'City', 'Category', 'Quantity', 'Price'], dtype='object')

In [0]:
sales.index

RangeIndex(start=0, stop=6, step=1)

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.info()
# Generate Information for the sales df
# info() is one of the first commands you run when opening an unknown dataset.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   6 non-null      int64
 1   Customer  6 non-null      object
 2   City      6 non-null      object
 3   Category  6 non-null      object
 4   Quantity  6 non-null      int64
 5   Price     6 non-null      int64
dtypes: int64(3), object(3)
memory usage: 420.0+ bytes

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.describe()
# stats about numerical data

          OrderID  Quantity         Price
count    6.000000  6.000000      6.000000
mean   103.500000  2.333333  50833.333333
std      1.870829  1.505545  22675.243475
min    101.000000  1.000000  25000.000000
25%    102.250000  1.250000  33750.000000
50%    103.500000  2.000000  47500.000000
75%    104.750000  2.750000  68750.000000
max    106.000000  5.000000  80000.000000

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
# 1 column :
sales['OrderID']

0    101
1    102
2    103
3    104
4    105
5    106
Name: OrderID, dtype: int64

In [0]:
# 1 + col :
sales[['OrderID','City']]

   OrderID    City
0      101   Delhi
1      102  Mumbai
2      103   Delhi
3      104    Pune
4      105   Delhi
5      106  Mumbai

In [0]:
sales[['OrderID','City','Price']]

   OrderID    City  Price
0      101   Delhi  75000
1      102  Mumbai  45000
2      103   Delhi  30000
3      104    Pune  80000
4      105   Delhi  50000
5      106  Mumbai  25000

In [0]:
sales.dtypes
# column name and their data types

OrderID      int64
Customer    object
City        object
Category    object
Quantity     int64
Price        int64
dtype: object

In [0]:
# Indexing and Slicing in Pandas DF :

In [0]:
# i. iloc
# ii. loc

In [0]:
# 1. iloc : integer based indexing!

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
print(sales.iloc[0,0]) # 0th row, 0th col index : 1st row, 1st col

101

In [0]:
print(sales.iloc[2,3]) # 2nd row, 3rd col index : 3rd row, 4th col

Tablet

In [0]:
# 2. loc : label based indexing

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.loc[0,['Customer','Price']]

Customer    Sankara
Price         75000
Name: 0, dtype: object

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
# Filter on laptop category
sales['Category'] == 'Laptop'

0     True
1    False
2    False
3     True
4    False
5    False
Name: Category, dtype: bool

In [0]:
sales[sales['Category'] == 'Laptop']

   OrderID Customer   City Category  Quantity  Price
0      101  Sankara  Delhi   Laptop         2  75000
3      104    Sneha   Pune   Laptop         1  80000

In [0]:
sales[sales['Price'] < 50000]
# sales[] => filter condition within brackers.

   OrderID Customer    City Category  Quantity  Price
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
# And clause :
sales[
    (sales["City"]=="Delhi") &
    (sales["Price"]>40000)

]

   OrderID Customer   City Category  Quantity  Price
0      101  Sankara  Delhi   Laptop         2  75000
4      105    Rahul  Delhi    Phone         2  50000

In [0]:
# & : and
# | : or

In [0]:
# Question 1
# Display only Customer and Category.

# Question 2
# Find all Phone orders.

# Question 3
# Find all orders from Delhi.

# Question 4
# Display the first three rows.

# Question 5
# How many rows and columns are present?

In [0]:
# Question 1
# Display only Customer and Category.
sales[['Customer','Category']]

  Customer Category
0  Sankara   Laptop
1    Priya    Phone
2    Rohit   Tablet
3    Sneha   Laptop
4    Rahul    Phone
5     Neha   Tablet

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
# Question 2
# Find all Phone orders.
sales[sales['Category'] == 'Phone']

   OrderID Customer    City Category  Quantity  Price
1      102    Priya  Mumbai    Phone         1  45000
4      105    Rahul   Delhi    Phone         2  50000

In [0]:
# Question 3
# Find all orders from Delhi.
sales[sales['City'] == 'Delhi']

   OrderID Customer   City Category  Quantity  Price
0      101  Sankara  Delhi   Laptop         2  75000
2      103    Rohit  Delhi   Tablet         3  30000
4      105    Rahul  Delhi    Phone         2  50000

In [0]:
# Question 4
# Display the first three rows.
sales.head(4)

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000

In [0]:
# Question 5
# How many rows and columns are present?
sales.shape
sales.dtypes
type(sales)
#sales.ndim
#sales.axes
#sales.columns
#sales.index
#sales.values
# sales.describe()
sales.head()
sales.tail()
sales.iloc[2,3]

'Tablet'