In [0]:
# NumPy : numerical python, array, mathematical operation!
# pythonic data types : list tuples sets dict
# numpy : array

In [0]:
# Why Pandas?

# How many of you have used excel? Excel has limitation when data is large.

# Suppose :
# 50 million customers
# 100 csv files
# Need some automation

# Using excel in this scenario becomes challenging.

# Pandas allows us to :
# 1. Read data
# 2. Clean data
# 3. Transform data
# 4. Analyse data
# 5. Export results

# Think of Pandas - Excel of Steroids using python!

In [0]:
# What is structured data?
# Rows and columns (Tabular Data)

In [0]:
import numpy  as np
import pandas as pd

In [0]:
# 1. Series : One column!
age = pd.Series([20,22,24,26,28,30,32])
print(age)

0    20
1    22
2    24
3    26
4    28
5    30
6    32
dtype: int64

In [0]:
# A series has 2 things : i) Index ii) Values

In [0]:
# 2. Dataframe : Multiple Series together!
students = pd.DataFrame(
    {
        'Name' : ['a','b','c','d','e'],
        'Age'  : [20,30,40,50,60],
        'Marks': [80,70,60,50,40]
    }
)

In [0]:
students

  Name  Age  Marks
0    a   20     80
1    b   30     70
2    c   40     60
3    d   50     50
4    e   60     40

In [0]:
type(students)

pandas.core.frame.DataFrame

In [0]:
students['Name'] # fetch name column from a student df

0    a
1    b
2    c
3    d
4    e
Name: Name, dtype: object

In [0]:
type(students['Name'])

pandas.core.series.Series

In [0]:
students['Name'].values

array(['a', 'b', 'c', 'd', 'e'], dtype=object)

In [0]:
sales = pd.DataFrame({
    "OrderID":[101,102,103,104,105,106],
    "Customer":["Sankara","Priya","Rohit","Sneha","Rahul","Neha"],
    "City":["Delhi","Mumbai","Delhi","Pune","Delhi","Mumbai"],
    "Category":["Laptop","Phone","Tablet","Laptop","Phone","Tablet"],
    "Quantity":[2,1,3,1,2,5],
    "Price":[75000,45000,30000,80000,50000,25000]
})

sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.head() # default : first 5 rows

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000

In [0]:
sales.head(1) # first row

   OrderID Customer   City Category  Quantity  Price
0      101  Sankara  Delhi   Laptop         2  75000

In [0]:
sales.tail() # default : last 5 rows

   OrderID Customer    City Category  Quantity  Price
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.tail(1) # last row in the output

   OrderID Customer    City Category  Quantity  Price
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.shape
# rows, columns

(6, 6)

In [0]:
sales.columns

Index(['OrderID', 'Customer', 'City', 'Category', 'Quantity', 'Price'], dtype='object')

In [0]:
sales.index

RangeIndex(start=0, stop=6, step=1)

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.info()
# Generate Information for the sales df
# info() is one of the first commands you run when opening an unknown dataset.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   6 non-null      int64
 1   Customer  6 non-null      object
 2   City      6 non-null      object
 3   Category  6 non-null      object
 4   Quantity  6 non-null      int64
 5   Price     6 non-null      int64
dtypes: int64(3), object(3)
memory usage: 420.0+ bytes

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.describe()
# stats about numerical data

          OrderID  Quantity         Price
count    6.000000  6.000000      6.000000
mean   103.500000  2.333333  50833.333333
std      1.870829  1.505545  22675.243475
min    101.000000  1.000000  25000.000000
25%    102.250000  1.250000  33750.000000
50%    103.500000  2.000000  47500.000000
75%    104.750000  2.750000  68750.000000
max    106.000000  5.000000  80000.000000

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
# 1 column :
sales['OrderID']

0    101
1    102
2    103
3    104
4    105
5    106
Name: OrderID, dtype: int64

In [0]:
# 1 + col :
sales[['OrderID','City']]

   OrderID    City
0      101   Delhi
1      102  Mumbai
2      103   Delhi
3      104    Pune
4      105   Delhi
5      106  Mumbai

In [0]:
sales[['OrderID','City','Price']]

   OrderID    City  Price
0      101   Delhi  75000
1      102  Mumbai  45000
2      103   Delhi  30000
3      104    Pune  80000
4      105   Delhi  50000
5      106  Mumbai  25000

In [0]:
sales.dtypes
# column name and their data types

OrderID      int64
Customer    object
City        object
Category    object
Quantity     int64
Price        int64
dtype: object

In [0]:
# Indexing and Slicing in Pandas DF :

In [0]:
# i. iloc
# ii. loc

In [0]:
# 1. iloc : integer based indexing!

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
print(sales.iloc[0,0]) # 0th row, 0th col index : 1st row, 1st col

101

In [0]:
print(sales.iloc[2,3]) # 2nd row, 3rd col index : 3rd row, 4th col

Tablet

In [0]:
# 2. loc : label based indexing

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
sales.loc[0,['Customer','Price']]

Customer    Sankara
Price         75000
Name: 0, dtype: object

In [0]:
sales

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
# Filter on laptop category
sales['Category'] == 'Laptop'

0     True
1    False
2    False
3     True
4    False
5    False
Name: Category, dtype: bool

In [0]:
sales[sales['Category'] == 'Laptop']

   OrderID Customer   City Category  Quantity  Price
0      101  Sankara  Delhi   Laptop         2  75000
3      104    Sneha   Pune   Laptop         1  80000

In [0]:
sales[sales['Price'] < 50000]
# sales[] => filter condition within brackers.

   OrderID Customer    City Category  Quantity  Price
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
5      106     Neha  Mumbai   Tablet         5  25000

In [0]:
# And clause :
sales[
    (sales["City"]=="Delhi") &
    (sales["Price"]>40000)

]

   OrderID Customer   City Category  Quantity  Price
0      101  Sankara  Delhi   Laptop         2  75000
4      105    Rahul  Delhi    Phone         2  50000

In [0]:
# & : and
# | : or

In [0]:
# Question 1
# Display only Customer and Category.
sales[["Customer","Category"]]

  Customer Category
0  Sankara   Laptop
1    Priya    Phone
2    Rohit   Tablet
3    Sneha   Laptop
4    Rahul    Phone
5     Neha   Tablet

In [0]:
# Question 2
# Find all Phone orders.
sales[sales["Category"]=="Phone"]

   OrderID Customer    City Category  Quantity  Price
1      102    Priya  Mumbai    Phone         1  45000
4      105    Rahul   Delhi    Phone         2  50000

In [0]:
# Question 3
# Find all orders from Delhi.
sales[sales["City"]=="Delhi"]

   OrderID Customer   City Category  Quantity  Price
0      101  Sankara  Delhi   Laptop         2  75000
2      103    Rohit  Delhi   Tablet         3  30000
4      105    Rahul  Delhi    Phone         2  50000

In [0]:
# Question 4
# Display the first three rows.
sales.head(3)

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000

In [0]:
# Question 5
# How many rows and columns are present?
sales.shape

(6, 6)

In [0]:
# Rows :
sales.shape[0]

6

In [0]:
# Columns :
sales.shape[1]

9

In [0]:
# Hour 2 :
# Using Sales dataframe!

In [0]:
sales.head()

   OrderID Customer    City Category  Quantity  Price
0      101  Sankara   Delhi   Laptop         2  75000
1      102    Priya  Mumbai    Phone         1  45000
2      103    Rohit   Delhi   Tablet         3  30000
3      104    Sneha    Pune   Laptop         1  80000
4      105    Rahul   Delhi    Phone         2  50000

In [0]:
# Quantity and Price
# total amount = Quantity x Price

In [0]:
sales['Total'] = sales['Quantity']*sales['Price']

# Pandas perform : vectorized operation :
# it works on the entire column at once instead of looping row by row.

In [0]:
sales.head()

   OrderID CustomerName    City Category  ...  Price   Total  Discount  NetAmount
0      101      Sankara   Delhi   Laptop  ...  75000  150000   15000.0   135000.0
1      106         Neha  Mumbai   Tablet  ...  25000  125000   12500.0   112500.0
2      105        Rahul   Delhi    Phone  ...  50000  100000   10000.0    90000.0
3      103        Rohit   Delhi   Tablet  ...  30000   90000    9000.0    81000.0
4      104        Sneha    Pune   Laptop  ...  80000   80000    8000.0    72000.0

[5 rows x 9 columns]

In [0]:
sales['Discount'] = sales['Total']*0.10

In [0]:
sales

   OrderID CustomerName    City Category  ...  Price   Total  Discount  NetAmount
0      101      Sankara   Delhi   Laptop  ...  75000  150000   15000.0   135000.0
1      106         Neha  Mumbai   Tablet  ...  25000  125000   12500.0   112500.0
2      105        Rahul   Delhi    Phone  ...  50000  100000   10000.0    90000.0
3      103        Rohit   Delhi   Tablet  ...  30000   90000    9000.0    81000.0
4      104        Sneha    Pune   Laptop  ...  80000   80000    8000.0    72000.0
5      102        Priya  Mumbai    Phone  ...  45000   45000    4500.0    40500.0

[6 rows x 9 columns]

In [0]:
sales['NetAmount'] = sales['Total'] - sales['Discount']

In [0]:
sales

   OrderID CustomerName    City Category  ...  Price   Total  Discount  NetAmount
0      101      Sankara   Delhi   Laptop  ...  75000  150000   15000.0   135000.0
1      106         Neha  Mumbai   Tablet  ...  25000  125000   12500.0   112500.0
2      105        Rahul   Delhi    Phone  ...  50000  100000   10000.0    90000.0
3      103        Rohit   Delhi   Tablet  ...  30000   90000    9000.0    81000.0
4      104        Sneha    Pune   Laptop  ...  80000   80000    8000.0    72000.0
5      102        Priya  Mumbai    Phone  ...  45000   45000    4500.0    40500.0

[6 rows x 9 columns]

In [0]:
# Conditional columns!

In [0]:
sales

   OrderID CustomerName    City Category  ...  Price   Total  Discount  NetAmount
0      101      Sankara   Delhi   Laptop  ...  75000  150000   15000.0   135000.0
1      106         Neha  Mumbai   Tablet  ...  25000  125000   12500.0   112500.0
2      105        Rahul   Delhi    Phone  ...  50000  100000   10000.0    90000.0
3      103        Rohit   Delhi   Tablet  ...  30000   90000    9000.0    81000.0
4      104        Sneha    Pune   Laptop  ...  80000   80000    8000.0    72000.0
5      102        Priya  Mumbai    Phone  ...  45000   45000    4500.0    40500.0

[6 rows x 9 columns]

In [0]:
# Premium : Price > 50000 --> Yes, else No!

In [0]:
sales['Premium'] = np.where(
    sales['Price'] > 50000,
    "Yes",
    "No"
)

In [0]:
sales

   OrderID CustomerName    City Category  ...   Total  Discount  NetAmount  Premium
0      101      Sankara   Delhi   Laptop  ...  150000   15000.0   135000.0      Yes
1      106         Neha  Mumbai   Tablet  ...  125000   12500.0   112500.0       No
2      105        Rahul   Delhi    Phone  ...  100000   10000.0    90000.0       No
3      103        Rohit   Delhi   Tablet  ...   90000    9000.0    81000.0       No
4      104        Sneha    Pune   Laptop  ...   80000    8000.0    72000.0      Yes
5      102        Priya  Mumbai    Phone  ...   45000    4500.0    40500.0       No

[6 rows x 10 columns]

In [0]:
# String Operations :

In [0]:
sales['CustomerName']

0    Sankara
1       Neha
2      Rahul
3      Rohit
4      Sneha
5      Priya
Name: CustomerName, dtype: object

In [0]:
# 1. Upper :
sales["CustomerName"].str.upper()

0    SANKARA
1       NEHA
2      RAHUL
3      ROHIT
4      SNEHA
5      PRIYA
Name: CustomerName, dtype: object

In [0]:
# 2. Lower :
sales["CustomerName"].str.lower()

0    sankara
1       neha
2      rahul
3      rohit
4      sneha
5      priya
Name: CustomerName, dtype: object

In [0]:
# 3. Length
sales["CustomerName"].str.len()

0    7
1    4
2    5
3    5
4    5
5    5
Name: CustomerName, dtype: int64

In [0]:
# 4. startswith
sales[
    sales["CustomerName"].str.startswith("S")
]

   OrderID CustomerName   City Category  ...   Total  Discount  NetAmount  Premium
0      101      Sankara  Delhi   Laptop  ...  150000   15000.0   135000.0      Yes
4      104        Sneha   Pune   Laptop  ...   80000    8000.0    72000.0      Yes

[2 rows x 10 columns]

In [0]:
# .str : provides vectorized string operations.

In [0]:
# Missing values :

In [0]:
employees = pd.DataFrame({
    "Employee":["Aman","Priya","Rahul","Neha","Sneha"],
    "Age":[24,np.nan,30,28,np.nan],
    "Salary":[40000,50000,np.nan,55000,45000],
    "Department":["HR","IT","IT",np.nan,"Finance"]
})

employees

  Employee   Age   Salary Department
0     Aman  24.0  40000.0         HR
1    Priya   NaN  50000.0         IT
2    Rahul  30.0      NaN         IT
3     Neha  28.0  55000.0        NaN
4    Sneha   NaN  45000.0    Finance

In [0]:
# NaN : not a number / missing value

In [0]:
# Detect missing value!
employees.isnull()

   Employee    Age  Salary  Department
0     False  False   False       False
1     False   True   False       False
2     False  False    True       False
3     False  False   False        True
4     False   True   False       False

In [0]:
# Column wise sum of missing value!
employees.isnull().sum()

Employee      0
Age           2
Salary        1
Department    1
dtype: int64

In [0]:
employees

  Employee   Age   Salary Department
0     Aman  24.0  40000.0         HR
1    Priya   NaN  50000.0         IT
2    Rahul  30.0      NaN         IT
3     Neha  28.0  55000.0        NaN
4    Sneha   NaN  45000.0    Finance

In [0]:
# employees.dropna()
# rows containing NaN values

In [0]:
# Filling missing values :
employees['Age']

0    24.0
1     NaN
2    30.0
3    28.0
4     NaN
Name: Age, dtype: float64

In [0]:
# numerical : mean / median / 0 / -100
employees['Age'].fillna(
    employees['Age'].mean(),
    inplace=True
)

In [0]:
employees['Age']

0    24.000000
1    27.333333
2    30.000000
3    28.000000
4    27.333333
Name: Age, dtype: float64

In [0]:
# salary : median
employees["Salary"].fillna(
    employees["Salary"].median(),
    inplace=True
)

/home/spark-d240d90f-6d2a-4127-99fb-7d/.ipykernel/313/command-5254598524642412-3582868030:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employees["Salary"].fillna(

In [0]:
employees["Salary"]

0    40000.0
1    50000.0
2    47500.0
3    55000.0
4    45000.0
Name: Salary, dtype: float64

In [0]:
# categorical value : mode / 'unknown

In [0]:
employees["Department"]

0         HR
1         IT
2         IT
3        NaN
4    Finance
Name: Department, dtype: object

In [0]:
employees["Department"].fillna("Unknown",inplace=True)

In [0]:
employees["Department"]

0         HR
1         IT
2         IT
3    Unknown
4    Finance
Name: Department, dtype: object

In [0]:
# Structural Operations :

In [0]:
sales.head()

   OrderID CustomerName    City Category  ...   Total  Discount  NetAmount  Premium
0      101      Sankara   Delhi   Laptop  ...  150000   15000.0   135000.0      Yes
1      106         Neha  Mumbai   Tablet  ...  125000   12500.0   112500.0       No
2      105        Rahul   Delhi    Phone  ...  100000   10000.0    90000.0       No
3      103        Rohit   Delhi   Tablet  ...   90000    9000.0    81000.0       No
4      104        Sneha    Pune   Laptop  ...   80000    8000.0    72000.0      Yes

[5 rows x 10 columns]

In [0]:
# 1. Rename colaumns :
sales = sales.rename(
    columns = {
        'Customer' : 'CustomerName',
    }
)

In [0]:
sales.head()

   OrderID CustomerName    City Category  ...   Total  Discount  NetAmount  Premium
0      101      Sankara   Delhi   Laptop  ...  150000   15000.0   135000.0      Yes
1      106         Neha  Mumbai   Tablet  ...  125000   12500.0   112500.0       No
2      105        Rahul   Delhi    Phone  ...  100000   10000.0    90000.0       No
3      103        Rohit   Delhi   Tablet  ...   90000    9000.0    81000.0       No
4      104        Sneha    Pune   Laptop  ...   80000    8000.0    72000.0      Yes

[5 rows x 10 columns]

In [0]:
# 2. Drop the column
sales = sales.drop(
    columns = ['Premium']
)

In [0]:
sales

   OrderID CustomerName    City Category  ...  Price   Total  Discount  NetAmount
0      101      Sankara   Delhi   Laptop  ...  75000  150000   15000.0   135000.0
1      102        Priya  Mumbai    Phone  ...  45000   45000    4500.0    40500.0
2      103        Rohit   Delhi   Tablet  ...  30000   90000    9000.0    81000.0
3      104        Sneha    Pune   Laptop  ...  80000   80000    8000.0    72000.0
4      105        Rahul   Delhi    Phone  ...  50000  100000   10000.0    90000.0
5      106         Neha  Mumbai   Tablet  ...  25000  125000   12500.0   112500.0

[6 rows x 9 columns]

In [0]:
# 3. Sort the dataframe
sales.sort_values(by='NetAmount',inplace=True) # asc sort!
sales

   OrderID CustomerName    City Category  ...  Price   Total  Discount  NetAmount
5      102        Priya  Mumbai    Phone  ...  45000   45000    4500.0    40500.0
4      104        Sneha    Pune   Laptop  ...  80000   80000    8000.0    72000.0
3      103        Rohit   Delhi   Tablet  ...  30000   90000    9000.0    81000.0
2      105        Rahul   Delhi    Phone  ...  50000  100000   10000.0    90000.0
1      106         Neha  Mumbai   Tablet  ...  25000  125000   12500.0   112500.0
0      101      Sankara   Delhi   Laptop  ...  75000  150000   15000.0   135000.0

[6 rows x 9 columns]

In [0]:
sales.sort_values(by='NetAmount',inplace=True, ascending=False) # desc sort!
sales

   OrderID CustomerName    City Category  ...  Price   Total  Discount  NetAmount
0      101      Sankara   Delhi   Laptop  ...  75000  150000   15000.0   135000.0
1      106         Neha  Mumbai   Tablet  ...  25000  125000   12500.0   112500.0
2      105        Rahul   Delhi    Phone  ...  50000  100000   10000.0    90000.0
3      103        Rohit   Delhi   Tablet  ...  30000   90000    9000.0    81000.0
4      104        Sneha    Pune   Laptop  ...  80000   80000    8000.0    72000.0
5      102        Priya  Mumbai    Phone  ...  45000   45000    4500.0    40500.0

[6 rows x 9 columns]

In [0]:
sales.sort_values(by='NetAmount',inplace=True,
                  ascending=False, ignore_index=True)
sales

   OrderID CustomerName    City Category  ...  Price   Total  Discount  NetAmount
0      101      Sankara   Delhi   Laptop  ...  75000  150000   15000.0   135000.0
1      106         Neha  Mumbai   Tablet  ...  25000  125000   12500.0   112500.0
2      105        Rahul   Delhi    Phone  ...  50000  100000   10000.0    90000.0
3      103        Rohit   Delhi   Tablet  ...  30000   90000    9000.0    81000.0
4      104        Sneha    Pune   Laptop  ...  80000   80000    8000.0    72000.0
5      102        Priya  Mumbai    Phone  ...  45000   45000    4500.0    40500.0

[6 rows x 9 columns]

In [0]:
# 2 ways :
# i.  inplace=True
# ii. df = df.rename

In [0]:
# sales.sort_values(
#     by=["City","Price"]
# )

In [0]:
# 4. drop duplicates
sales.drop_duplicates(inplace=True)

In [0]:
# specific column :
# sales.drop_duplicates(subset= 'column name',inplace=True)

In [0]:
# new = sales.describe()
# new

In [0]:
employees2 = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Name": ["Prathyusha", "Prathyusha", "Prathyusha", "Rahul"],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune"]
})

In [0]:
employees2

   ID        Name    City
0   1  Prathyusha   Delhi
1   2  Prathyusha  Mumbai
2   3  Prathyusha   Delhi
3   4       Rahul    Pune

In [0]:
employees2.drop_duplicates(subset=["Name"])

   ID        Name   City
0   1  Prathyusha  Delhi
3   4       Rahul   Pune

In [0]:
# Hands On :

In [0]:
# Part 1 :
import pandas as pd

sales = pd.DataFrame({
    "OrderID": [101,102,103,104,105,106,107,108],
    "Customer": ["Sankara","Priya","Rahul","Sneha","Priya","Rahul","Sankara","Neha"],
    "City": ["Delhi","Mumbai","Delhi","Pune","Mumbai","Delhi","Delhi","Pune"],
    "Category": ["Laptop","Phone","Phone","Laptop","Tablet","Laptop","Tablet","Phone"],
    "Amount": [80000,50000,35000,90000,25000,85000,30000,45000]
})

sales

   OrderID Customer    City Category  Amount
0      101  Sankara   Delhi   Laptop   80000
1      102    Priya  Mumbai    Phone   50000
2      103    Rahul   Delhi    Phone   35000
3      104    Sneha    Pune   Laptop   90000
4      105    Priya  Mumbai   Tablet   25000
5      106    Rahul   Delhi   Laptop   85000
6      107  Sankara   Delhi   Tablet   30000
7      108     Neha    Pune    Phone   45000

In [0]:
# Question 1
# Find the total sales (Amount) for each city.
# Question 2
# Find the average order amount for each product category.
# Question 3 (Multiple Aggregations)
# For each city, find:
# Total Sales
# Average Sales
# Maximum Sales
# Number of Orders

In [0]:
total_sales_by_city = sales.groupby('City')['Amount'].sum()
print(total_sales_by_city)

City
Delhi     230000
Mumbai     75000
Pune      135000
Name: Amount, dtype: int64

In [0]:
avg_order_amount_by_category = sales.groupby('Category')['Amount'].mean()
print(avg_order_amount_by_category)
# For each city, find:
# Total Sales
# Average Sales
# Maximum Sales
# Number of Orders
sales_by_city = sales.groupby('City').agg({
    'Amount': ['sum', 'mean', 'max', 'count']
})
print(sales_by_city)

Category
Laptop    85000.000000
Phone     43333.333333
Tablet    27500.000000
Name: Amount, dtype: float64
        Amount
           sum     mean    max count
City
Delhi   230000  57500.0  85000     4
Mumbai   75000  37500.0  50000     2
Pune    135000  67500.0  90000     2

In [0]:
# Part 2 :

In [0]:
customers = pd.DataFrame({
    "CustomerID": [1,2,3,4],
    "CustomerName": ["Sankara","Priya","Rahul","Sneha"],
    "City": ["Delhi","Mumbai","Delhi","Pune"]
})

orders = pd.DataFrame({
    "OrderID": [101,102,103,104,105],
    "CustomerID": [1,2,3,5,2],
    "Amount": [5000,7000,9000,6000,8000]
})

In [0]:
# Question 1
# Perform a Left Join between customers and orders. Which customers have not placed any order?
customers_left_join = pd.merge(customers, orders, on='CustomerID', how='left')
customers_left_join

   CustomerID CustomerName    City  OrderID  Amount
0           1      Sankara   Delhi    101.0  5000.0
1           2        Priya  Mumbai    102.0  7000.0
2           2        Priya  Mumbai    105.0  8000.0
3           3        Rahul   Delhi    103.0  9000.0
4           4        Sneha    Pune      NaN     NaN

In [0]:
orders

   OrderID  CustomerID  Amount
0      101           1    5000
1      102           2    7000
2      103           3    9000
3      104           5    6000
4      105           2    8000

In [0]:
# Question 2
# Perform an Outer Join. Which order belongs to a customer who is not present in the customer table?
#customers_outer_join = pd.merge(customers, orders, on='CustomerID', how='right')
customers_outer_join = customers.merge(orders, on='CustomerID', how='right')
customers_outer_join

   CustomerID CustomerName    City  OrderID  Amount
0           1      Sankara   Delhi      101    5000
1           2        Priya  Mumbai      102    7000
2           3        Rahul   Delhi      103    9000
3           5          NaN     NaN      104    6000
4           2        Priya  Mumbai      105    8000

In [0]:
# Question 3
# Perform a Right Join. Which customers have not placed any order?
customers_right_join = pd.merge(customers, orders, on='CustomerID', how='outer')
customers_right_join

   CustomerID CustomerName    City  OrderID  Amount
0           1      Sankara   Delhi    101.0  5000.0
1           2        Priya  Mumbai    102.0  7000.0
2           2        Priya  Mumbai    105.0  8000.0
3           3        Rahul   Delhi    103.0  9000.0
4           4        Sneha    Pune      NaN     NaN
5           5          NaN     NaN    104.0  6000.0